title: Juri Tschoell # your name (or website title) here
logo: "/images/foto.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Information Security Architect & Awareness Trainer
  <br><br>
  Send me a mail: <a href="mailto:mail(at)biz.tschoell.com">mail@biz.tschoell.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/juri-tschoell/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
